apiVersion: v1 
kind: Pod 
metadata: 
    name: test 
spec: 
  containers: 
  - name: app1 
    image: python:3.6-alpine 
    command: ['sh', '-c', 'echo cont1 > index.html && python -m http.server 8082'] 
  - name: app2 
    image: python:3.6-alpine 
    command: ['sh', '-c', 'echo cont2 > index.html && python -m http.server 8082']
